version: 2

jobs:
  publish_docker:
    working_directory: ~/project
    machine:
      image: ubuntu-2404:current
    steps:
      - checkout
      - run:
          name: Build docker
          command: docker build --force-rm -t dsarchive/histomicstk_similarity .
      - run:
          name: Publish images to Docker Hub
          command: |
              echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
              docker push dsarchive/histomicstk_similarity:latest
              if [[ $CIRCLE_TAG =~ ^v.*$ ]]; then
              docker tag dsarchive/histomicstk_similarity:latest "dsarchive/histomicstk_similarity:$CIRCLE_TAG"
              docker push "dsarchive/histomicstk_similarity:$CIRCLE_TAG"
              fi

workflows:
  version: 2

  ci:
    jobs:
      - publish_docker:
          filters:
            tags:
              only: /^v.*/
            branches:
              only:
                - master
